// <auto-generated />
namespace GestionProductosMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class proyectomaxi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(proyectomaxi));
        
        string IMigrationMetadata.Id
        {
            get { return "201811272259008_proyectomaxi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
